const picBank = [
    "/andy-holmes-sym5TTE2ks0-unsplash.jpg",
    "/autumn-studio-gsyUo-_cU94-unsplash.jpg",
    "/carl-raw-_NEzKE6Zdp4-unsplash.jpg",
    "/finn-hackshaw-FQgI8AD-BSg-unsplash.jpg",
    "/francois-olwage--KLKu_pruJ4-unsplash.jpg",
    "/gradienta-QWutu2BRpOs-unsplash.jpg",
    "/hector-achautla-Szyj_xzcZlg-unsplash.jpg",
    "/hello-i-m-nik-K_qGVldtzk0-unsplash.jpg",
    "/karalina-s-8V7ymFP8-0M-unsplash.jpg",
    "/marra-m7fT6OreZfI-unsplash.jpg",
    "/martin-woortman-Wtr39iVfzpw-unsplash.jpg",
    "/mike-von-v9-ZW3VONcw-unsplash.jpg",
    "/muhammad-saushan-lheYsXRi2Fc-unsplash.jpg",
    "/nathan-dumlao-WDjNsJWIxVE-unsplash.jpg",
    "/nio-milano-caH-ZLrisZA-unsplash.jpg",
    "/oleg-laptev-QRKJwE6yfJo-unsplash.jpg",
    "/z_img_design_05.JPG",
    "/z_img_design_class03.jpg",
    "/z_img_design_class02.jpg",
    "/Z_img_design_class01.png",
    "/big_hexes.JPG",
    "/bigblue.JPG",
    "/bigGreen.JPG",
    "/bigred.JPG",
    "/bigredreversed.jpg.JPG",
    "/bigyellow.JPG",
    "/hexes_blue_gradient_scan.JPG",
    "/hand_write.JPG"
];

export default picBank;